<a href="https://colab.research.google.com/github/KCMcafe15/Block-4-Task-4/blob/main/Block_4_Topic_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (Numeric Python) Library

NumPy is a Python library used for working with arrays. It also has functions for working in the domain of linear algebra, fourier transform, and matrices.

In [ ]:
# importing numpy

import numpy as np

Importing Package Index

In [ ]:
# importing an entire module

import math
print(math.sqrt(16))

# This code does two things:
# import math: This line imports the math module, which provides mathematical functions defined by the C standard. By importing math, you’re able to use these functions in your code.
#print(math.sqrt(16)): This line uses the sqrt function from the math module to calculate the square root of 16.
# The sqrt function returns the square root of the number you pass to it. In this case, the square root of 16 is 4.
# The print function then outputs this result (4) to the console.
#So, when you run this code, it will print out ‘4’ because that’s the square root of 16.

4.0


In [ ]:
# import a specific function or class from a module

from math import sqrt
print(sqrt(16))

4.0


In [ ]:
# import entire module with an alias

import math as m
print(m.sqrt(16))

4.0


Arrays

An array is a special variable, which can hold more than one value at a time.

In [ ]:
# creating arrays

topics = ["Google Sheets", "SQL", "Tableau", "Python"]
print (topics)

['Google Sheets', 'SQL', 'Tableau', 'Python']


Array Methods:

Python has a set of built-in methods that you can use on lists/arrays.

append() -Adds an element at the end of the list

clear()	-Removes all the elements from the list

copy()	-Returns a copy of the list

count()	-Returns the number of elements with the specified value

extend()	-Add the elements of a list (or any iterable), to the end of the current list

index()	-Returns the index of the first element with the specified value

insert()	-Adds an element at the specified position

pop()	-Removes the element at the specified position

remove()	-Removes the first item with the specified value

reverse()	-Reverses the order of the list

sort()	-Sorts the list

In [ ]:
# creating numpy array with data type

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)

[1. 2. 3. 4. 5.]


In [ ]:
# creating matrix with numpy
# using data type

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print(m)

[[1 2 3]
 [4 5 6]]


In [ ]:
# creating a vector or matrix using the "ones" method

import numpy as np

a = np.ones((5,), dtype=float)
print(a)

m = np.ones((2, 3), dtype=int)
print(m)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [ ]:
# creating a vector or matrix using the "zeros" method

import numpy as np

a = np.zeros(5, dtype=float)
print(a)

m = np.zeros((2, 3), dtype=int)
print(m)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [ ]:
# dimension using shape

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.shape)

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print(m.shape)

(5,)
(2, 3)


In [ ]:
# dimension using size

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.size)

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print(m.size)

5
6


In [ ]:
# indexing vector

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[1:])
print(a[:2])

1
[2 3 4 5]
[1 2]


In [ ]:
# indexing matrix

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1, 1])
print(a[1:, 1])
print(a[0, :2])

5
[5 8]
[4 5]


In [ ]:
# arithmetic operations in vector

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

In [ ]:
# arithmetic operations in matrix

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

In [ ]:
# aggregation in vectors

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())

In [ ]:
# aggregation in matrix

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())

PANDAS

In [ ]:
# creating series (vector)

import pandas as pd

mountains_height = pd.Series([2061, 2035.8, 2028.5, 2022.5, 2016.4])

print(mountains_height)

0    2061.0
1    2035.8
2    2028.5
3    2022.5
4    2016.4
dtype: float64


In [ ]:
# creating series matrix

import pandas as pd

mountains_height = pd.Series(
    data=[2061, 2035.8, 2028.5, 2022.5, 2016.4],
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

print(mountains_height)

Goverla           2061.0
Brebenskyl        2035.8
Pip_Ivan          2028.5
Petros            2022.5
Gutin_Tomnatik    2016.4
Name: Height, m, dtype: float64


Indexing Series

In [ ]:
mountains_height = pd.Series(
    data=[2061, 2035.8, 2028.5, 2022.5, 2016.4],
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

print(mountains_height[0])
print(mountains_height["Goverla"])

2061.0
2061.0


In [ ]:
mountains_height = pd.Series(
    data=[2061, 2035.8, 2028.5, 2022.5, 2016.4],
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

print(mountains_height[["Pip_Ivan", "Goverla", "Gutin_Tomnatik"]])

Pip_Ivan          2028.5
Goverla           2061.0
Gutin_Tomnatik    2016.4
Name: Height, m, dtype: float64


In [ ]:
# Comparison and filtering operations of the Series object using logical operations create a new Series object

mountains_height = pd.Series(
    data=[2061, 2035.8, 2028.5, 2022.5, 2016.4],
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

print(mountains_height > 2030)
print(mountains_height[mountains_height > 2030])

Goverla            True
Brebenskyl         True
Pip_Ivan          False
Petros            False
Gutin_Tomnatik    False
Name: Height, m, dtype: bool
Goverla       2061.0
Brebenskyl    2035.8
Name: Height, m, dtype: float64


In [ ]:
# sort index

mountains_height = pd.Series(
    data=[2061, 2035.8, 2028.5, 2022.5, 2016.4],
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

sort_index = mountains_height.sort_index()
print(sort_index)

Brebenskyl        2035.8
Goverla           2061.0
Gutin_Tomnatik    2016.4
Petros            2022.5
Pip_Ivan          2028.5
Name: Height, m, dtype: float64


In [ ]:
# sort value

mountains_height = pd.Series(
    data=[2061, 2035.8, 2028.5, 2022.5, 2016.4],
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

mountains_height.sort_values(inplace=True, ascending=False)
print(mountains_height)

Goverla           2061.0
Brebenskyl        2035.8
Pip_Ivan          2028.5
Petros            2022.5
Gutin_Tomnatik    2016.4
Name: Height, m, dtype: float64


In [ ]:
# replacing NaN

import pandas as pd

mountains_height = pd.Series(
    {"Goverla": 2061, "Brebenskyl": 2035.8, "Pip_Ivan": 2028.5},
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

print(mountains_height)

mountains_height.fillna(0, inplace=True)

print(mountains_height)

Goverla           2061.0
Brebenskyl        2035.8
Pip_Ivan          2028.5
Petros               NaN
Gutin_Tomnatik       NaN
Name: Height, m, dtype: float64
Goverla           2061.0
Brebenskyl        2035.8
Pip_Ivan          2028.5
Petros               0.0
Gutin_Tomnatik       0.0
Name: Height, m, dtype: float64


Create and load data into a DataFrame:

A DataFrame is a two-dimensional labeled data structure with columns of potentially different types. It’s similar to a spreadsheet or SQL table, or a dictionary of Series objects. It is generally the most commonly used pandas object.

Here’s a brief explanation and an example:

Explanation: In Python, you can use the pandas library to create a DataFrame and load data into it. Data can be loaded from various sources such as a list, a dictionary, or a CSV file.

Example: Here’s an example of creating a DataFrame from a dictionary:

In [ ]:
import pandas as pd

# Create a dictionary
data = {
    'Name': ['John', 'Anna', 'Peter'],
    'Age': [28, 24, 22],
}

# Load data into a DataFrame
df = pd.DataFrame(data)

# Print the DataFrame
print(df)


    Name  Age
0   John   28
1   Anna   24
2  Peter   22


DataFrame methods and attributes:

1. head(): This function returns the first n rows for the DataFrame. By default, it returns the first 5 rows.

Example:

In [ ]:
print(df.head())

2. tail(): This function returns the last n rows for the DataFrame. By default, it returns the last 5 rows.

Example:

In [ ]:
print(df.tail())

3. shape: This attribute returns a tuple representing the dimensionality of the DataFrame. The first element of the tuple is the number of rows and the second element is the number of columns.

Example:

In [ ]:
print(df.shape)

4. info(): This method prints information about a DataFrame including the index dtype and columns, non-null values, and memory usage.

Example:

In [ ]:
print(df.info())

5. describe(): This function generates descriptive statistics of a DataFrame. For numerical data, the result’s index will include count, mean, std, min, 25%, 50%, 75%, max. For object data (e.g. strings or timestamps), the result’s index will include count, unique, top, freq.

Example:

In [ ]:
print(df.describe())

6. columns: This attribute returns the column labels of the DataFrame.

Example:

In [ ]:
print(df.columns)

7. dtypes: This attribute returns the dtypes in the DataFrame. It returns a Series with the data type of each column.

Example:

In [ ]:
print(df.dtypes)

DataFrame editing operations:

1. Changing the Index: You can change the index of a DataFrame using the set_index method. This method sets the DataFrame index using existing columns.

Example:

In [ ]:
# Set 'Name' as the index
df.set_index('Name', inplace=True)
print(df)

       Age
Name      
John    28
Anna    24
Peter   22


2. Changing Column Names: You can change the column names of a DataFrame by assigning a new list of column names to the columns attribute.

Example:

In [ ]:
# Change column names
df.columns = ['New_Name', 'New_Age']
print(df)

3. Deleting Columns: You can delete columns from a DataFrame using the drop method. You need to specify the axis parameter as 1 or 'columns'.

Example:

In [ ]:
# Delete the 'New_Age' column
df.drop('New_Age', axis=1, inplace=True)
print(df)

Remember, the inplace=True argument makes the change in the existing DataFrame. If you don’t use inplace=True, the methods will return a new DataFrame with the changes, and the original DataFrame will remain unchanged.

How to access DataFrame columns:

Accessing DataFrame Columns: You can access the columns of a DataFrame using the column labels. There are two main ways to do this:

Dictionary-like style: You can use the column label as a key, similar to how you access values in a dictionary.
Example:

In [ ]:
# Access the 'Name' column
name_column = df['Name']
print(name_column)

Attribute style: If the column label is a valid Python identifier, you can also use attribute-style accessing with dot notation. However, this method won’t work for column labels that contain spaces or special characters, or that conflict with DataFrame methods.

In [ ]:
# Access the 'Age' column
age_column = df.Age
print(age_column)

In both cases, the result is a pandas Series object containing the data of the specified column.

How to work with missing data in a DataFrame:

1. isnull(): This function is used to check and manage NULL values in a data frame. It returns a DataFrame of booleans showing whether each element in the DataFrame is an NA value.

In [ ]:
# Check for NULL values
print(df.isnull())

2. dropna(): This function removes missing values. It removes all the rows that contain a missing value.

Example:

In [ ]:
# Remove rows with NULL values
df_clean = df.dropna()
print(df_clean)

3. fillna(): This function replaces the missing values with a specified value or method (such as 'mean', 'median', 'mode', 'ffill', 'bfill').

Example:

In [ ]:
# Replace NULL values with a specific value
df_filled = df.fillna(0)
print(df_filled)

4. replace(): This function replaces a set of values with another set of values. It can be used to replace not only missing values but also other values in the DataFrame.

Example:

In [ ]:
# Replace specific values
df_replaced = df.replace('Unknown', 'N/A')
print(df_replaced)

Using “Chains” of Methods:

In pandas, you can chain methods together to perform more complex data manipulations. This is often referred to as “method chaining”. Each method operates on the DataFrame and returns a new DataFrame, allowing the operations to be chained together in a single statement.

Here’s an example:

In [ ]:
# Load data, drop missing values, and calculate the mean
mean_value = df['column_name'].dropna().mean()
print(mean_value)

In this example, df['column_name'] selects a column from the DataFrame, dropna() removes any rows with missing values in that column, and mean() calculates the mean of the remaining values. All of these operations are performed in a single line of code.